---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    version: 1.0.0
  name: demo-prod
  namespace: demo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      version: 1.0.0
  template:
    metadata:
      labels:
        app: demo
        version: 1.0.0
    spec:
      containers:
        - name: canary-demo
          image: haseebsultan/dotnetcore:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
          env:
            - name: VERSION
              value: "1.0.0"
      restartPolicy: Always
